# Generated by Django 5.2.3 on 2026-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('audio', models.FileField(upload_to='audio/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
