# Generated by Django 6.0.2 on 2026-02-06 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audiomessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audio Message', 'verbose_name_plural': 'Audio Messages'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Duration of audio in seconds', null=True),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='file_size_mb',
            field=models.FloatField(blank=True, help_text='Size of audio file in MB', null=True),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='is_audio_transcribed',
            field=models.BooleanField(default=False, help_text='Whether this message was transcribed from audio'),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='audio',
            field=models.FileField(help_text='Audio file from microphone recording', upload_to='audio/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'flac'])]),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when audio was uploaded'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='original_text',
            field=models.TextField(help_text='Original message in source language'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when message was created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='translated_text',
            field=models.TextField(help_text='Translated message in target language'),
        ),
        migrations.AddIndex(
            model_name='audiomessage',
            index=models.Index(fields=['role', '-timestamp'], name='api_audiome_role_5fcac4_idx'),
        ),
        migrations.AddIndex(
            model_name='audiomessage',
            index=models.Index(fields=['-timestamp'], name='api_audiome_timesta_373906_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role', '-timestamp'], name='api_message_role_bde9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-timestamp'], name='api_message_timesta_97ab18_idx'),
        ),
    ]
