# Generated by Django 5.2.3 on 2026-02-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audiomessage_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='audiomessage',
            name='api_audiome_role_5fcac4_idx',
        ),
        migrations.RemoveIndex(
            model_name='audiomessage',
            name='api_audiome_timesta_373906_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_role_bde9a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_timesta_97ab18_idx',
        ),
        migrations.RemoveField(
            model_name='audiomessage',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='audiomessage',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='audiomessage',
            name='file_size_mb',
        ),
        migrations.RemoveField(
            model_name='audiomessage',
            name='transcription_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_audio_transcribed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='translated_text',
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_messages/'),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
